[project]
name = "multimodal-parser"
version = "0.1.0"
description = "Extract content from PDF documents using multimodal LLMs in markdown format"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.4",
    "ollama>=0.4.4",
    "pydantic>=2.10.3",
    "pymupdf>=1.25.1",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
    "pytest>=8.3.4",
    "ruff>=0.8.3",
]
